// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbNFapbTKIQVtTXTxQH8vJAaVQaAP5Jhw',
    appId: '1:545085974690:web:088518f71e8d5151d28ffb',
    messagingSenderId: '545085974690',
    projectId: 'smart-fintech-app',
    authDomain: 'smart-fintech-app.firebaseapp.com',
    storageBucket: 'smart-fintech-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB7VGuf4BXIpc3Dx3ro7c0UVHOuieDumo',
    appId: '1:545085974690:android:82415f04dbb71956d28ffb',
    messagingSenderId: '545085974690',
    projectId: 'smart-fintech-app',
    storageBucket: 'smart-fintech-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKCfrn8AVdll2yK81FK1DJm4-mrXUubkw',
    appId: '1:545085974690:ios:ccf9f8291edee5e0d28ffb',
    messagingSenderId: '545085974690',
    projectId: 'smart-fintech-app',
    storageBucket: 'smart-fintech-app.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKCfrn8AVdll2yK81FK1DJm4-mrXUubkw',
    appId: '1:545085974690:ios:ccf9f8291edee5e0d28ffb',
    messagingSenderId: '545085974690',
    projectId: 'smart-fintech-app',
    storageBucket: 'smart-fintech-app.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbNFapbTKIQVtTXTxQH8vJAaVQaAP5Jhw',
    appId: '1:545085974690:web:9d24a3d591ac2393d28ffb',
    messagingSenderId: '545085974690',
    projectId: 'smart-fintech-app',
    authDomain: 'smart-fintech-app.firebaseapp.com',
    storageBucket: 'smart-fintech-app.firebasestorage.app',
  );
}
